In [35]:
import pandas as pd
import torch

In [36]:
#read csv: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
veri = pd.read_csv("IMDB Dataset.csv")

In [37]:
veri.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [38]:
print(veri.columns)
print(veri.shape)
print(veri["sentiment"].value_counts())
veri_kucuk = veri.sample(n=2000, random_state=42).reset_index(drop=True)

Index(['review', 'sentiment'], dtype='str')
(50000, 2)
sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [39]:
veri_kucuk["label"] = veri_kucuk["sentiment"].map({
    "positive": 1,
    "negative": 0
})

In [40]:
veri_kucuk[["review", "sentiment", "label"]].head()

                                              review sentiment  label
0  I really liked this Summerslam due to the look...  positive      1
1  Not many television shows appeal to quite as m...  positive      1
2  The film quickly gets to a major chase scene w...  negative      0
3  Jane Austen would definitely approve of this o...  positive      1
4  Expectations were somewhat high for me when I ...  negative      0

In [41]:
from sklearn.model_selection import train_test_split

train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    veri_kucuk["review"].tolist(),
    veri_kucuk["label"].tolist(),
    test_size=0.2,
    random_state=44,
    stratify=veri_kucuk["label"]
)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts,
    temp_labels,
    test_size=0.5,
    random_state=44,
    stratify=temp_labels
)

In [42]:
#from transformers import AutoTokenizer, AutoModel
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import numpy as np

model_name = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained( model_name, num_labels=2)


#tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
#model = AutoModel.from_pretrained("bert-base-uncased")

model.eval()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [43]:
train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=256
)

val_encodings = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=256
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=256
)

In [44]:
train_dataset = IMDBDataset(train_encodings, train_labels)
val_dataset = IMDBDataset(val_encodings, val_labels)
test_dataset = IMDBDataset(test_encodings, test_labels)

In [45]:
import torch

class IMDBDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(self.labels[idx])

        return item

    def __len__(self):
        return len(self.labels)

In [46]:
train_dataset = IMDBDataset(train_encodings, train_labels)
test_dataset = IMDBDataset(test_encodings, test_labels)

In [47]:
from transformers import TrainingArguments, Trainer

In [48]:
training_args = TrainingArguments(
    output_dir="./bert_imdb_output",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=20,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

In [49]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="binary"
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

In [50]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

In [51]:
trainer.train()

c:\venv\bert\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

c:\venv\bert\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

c:\venv\bert\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=600, training_loss=0.31641422073046366, metrics={'train_runtime': 5671.4045, 'train_samples_per_second': 0.846, 'train_steps_per_second': 0.106, 'total_flos': 631466532864000.0, 'train_loss': 0.31641422073046366, 'epoch': 3.0})

In [52]:
trainer.evaluate()

c:\venv\bert\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.2724872827529907,
 'eval_accuracy': 0.915,
 'eval_precision': 0.8932038834951457,
 'eval_recall': 0.9387755102040817,
 'eval_f1': 0.9154228855721394}

In [53]:
print(veri_kucuk["label"].value_counts())
print(train_labels[:20])
print(test_labels[:20])

label
0    1024
1     976
Name: count, dtype: int64
[1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]
[1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1]

In [54]:
trainer.state.log_history

[{'loss': 0.7616782188415527,
  'grad_norm': 8.172735214233398,
  'learning_rate': 1.936666666666667e-05,
  'epoch': 0.1,
  'step': 20},
 {'loss': 0.6889323234558106,
  'grad_norm': 4.492760181427002,
  'learning_rate': 1.8700000000000004e-05,
  'epoch': 0.2,
  'step': 40},
 {'loss': 0.6903156757354736,
  'grad_norm': 3.7297415733337402,
  'learning_rate': 1.8033333333333332e-05,
  'epoch': 0.3,
  'step': 60},
 {'loss': 0.6684160709381104,
  'grad_norm': 6.493052005767822,
  'learning_rate': 1.7366666666666668e-05,
  'epoch': 0.4,
  'step': 80},
 {'loss': 0.5684875965118408,
  'grad_norm': 5.666116714477539,
  'learning_rate': 1.67e-05,
  'epoch': 0.5,
  'step': 100},
 {'loss': 0.473414945602417,
  'grad_norm': 6.023988246917725,
  'learning_rate': 1.6033333333333335e-05,
  'epoch': 0.6,
  'step': 120},
 {'loss': 0.41500306129455566,
  'grad_norm': 14.102923393249512,
  'learning_rate': 1.5366666666666666e-05,
  'epoch': 0.7,
  'step': 140},
 {'loss': 0.3562354803085327,
  'grad_norm': 5.605353832244873,
  'learning_rate': 1.4700000000000002e-05,
  'epoch': 0.8,
  'step': 160},
 {'loss': 0.3685903549194336,
  'grad_norm': 19.762088775634766,
  'learning_rate': 1.4033333333333335e-05,
  'epoch': 0.9,
  'step': 180},
 {'loss': 0.32598888874053955,
  'grad_norm': 7.301455974578857,
  'learning_rate': 1.3366666666666669e-05,
  'epoch': 1.0,
  'step': 200},
 {'eval_loss': 0.3695172071456909,
  'eval_accuracy': 0.85,
  'eval_precision': 0.7698412698412699,
  'eval_recall': 0.9897959183673469,
  'eval_f1': 0.8660714285714286,
  'eval_runtime': 45.3559,
  'eval_samples_per_second': 4.41,
  'eval_steps_per_second': 0.551,
  'epoch': 1.0,
  'step': 200},
 {'loss': 0.25046205520629883,
  'grad_norm': 0.8230054974555969,
  'learning_rate': 1.27e-05,
  'epoch': 1.1,
  'step': 220},
 {'loss': 0.2848529815673828,
  'grad_norm': 0.5980401039123535,
  'learning_rate': 1.2033333333333334e-05,
  'epoch': 1.2,
  'step': 240},
 {'loss': 0.31726484298706054,
  'grad_norm': 2.0508742332458496,
  'learning_rate': 1.1366666666666667e-05,
  'epoch': 1.3,
  'step': 260},
 {'loss': 0.23684582710266114,
  'grad_norm': 7.794430732727051,
  'learning_rate': 1.0700000000000001e-05,
  'epoch': 1.4,
  'step': 280},
 {'loss': 0.49371185302734377,
  'grad_norm': 44.501922607421875,
  'learning_rate': 1.0033333333333334e-05,
  'epoch': 1.5,
  'step': 300},
 {'loss': 0.23514795303344727,
  'grad_norm': 22.061084747314453,
  'learning_rate': 9.366666666666668e-06,
  'epoch': 1.6,
  'step': 320},
 {'loss': 0.27400434017181396,
  'grad_norm': 6.877014636993408,
  'learning_rate': 8.700000000000001e-06,
  'epoch': 1.7,
  'step': 340},
 {'loss': 0.25386526584625246,
  'grad_norm': 15.41490364074707,
  'learning_rate': 8.033333333333335e-06,
  'epoch': 1.8,
  'step': 360},
 {'loss': 0.2361302375793457,
  'grad_norm': 12.400002479553223,
  'learning_rate': 7.3666666666666676e-06,
  'epoch': 1.9,
  'step': 380},
 {'loss': 0.2669623136520386,
  'grad_norm': 2.248260498046875,
  'learning_rate': 6.700000000000001e-06,
  'epoch': 2.0,
  'step': 400},
 {'eval_loss': 0.27200472354888916,
  'eval_accuracy': 0.915,
  'eval_precision': 0.8932038834951457,
  'eval_recall': 0.9387755102040817,
  'eval_f1': 0.9154228855721394,
  'eval_runtime': 47.6064,
  'eval_samples_per_second': 4.201,
  'eval_steps_per_second': 0.525,
  'epoch': 2.0,
  'step': 400},
 {'loss': 0.12505544424057008,
  'grad_norm': 0.5733314156532288,
  'learning_rate': 6.033333333333335e-06,
  'epoch': 2.1,
  'step': 420},
 {'loss': 0.13173097372055054,
  'grad_norm': 0.24213434755802155,
  'learning_rate': 5.366666666666666e-06,
  'epoch': 2.2,
  'step': 440},
 {'loss': 0.12469862699508667,
  'grad_norm': 0.16621658205986023,
  'learning_rate': 4.7e-06,
  'epoch': 2.3,
  'step': 460},
 {'loss': 0.1724371552467346,
  'grad_norm': 40.822818756103516,
  'learning_rate': 4.033333333333333e-06,
  'epoch': 2.4,
  'step': 480},
 {'loss': 0.1815705418586731,
  'grad_norm': 0.20357532799243927,
  'learning_rate': 3.366666666666667e-06,
  'epoch': 2.5,
  'step': 500},
 {'loss': 0.13165069818496705,
  'grad_norm': 0.11804614216089249,
  'learning_rate': 2.7000000000000004e-06,
  'epoch': 2.6,
  'step': 520},
 {'loss': 0.08337968587875366,
  'grad_norm': 27.4355525970459,
  'learning_rate': 2.0333333333333335e-06,
  'epoch': 2.7,
  'step': 540},
 {'loss': 0.13633375167846679,
  'grad_norm': 0.8122232556343079,
  'learning_rate': 1.3666666666666668e-06,
  'epoch': 2.8,
  'step': 560},
 {'loss': 0.16794941425323487,
  'grad_norm': 0.2881026864051819,
  'learning_rate': 7.000000000000001e-07,
  'epoch': 2.9,
  'step': 580},
 {'loss': 0.07131004333496094,
  'grad_norm': 0.12846942245960236,
  'learning_rate': 3.333333333333334e-08,
  'epoch': 3.0,
  'step': 600},
 {'eval_loss': 0.39127877354621887,
  'eval_accuracy': 0.905,
  'eval_precision': 0.9157894736842105,
  'eval_recall': 0.8877551020408163,
  'eval_f1': 0.9015544041450777,
  'eval_runtime': 46.3726,
  'eval_samples_per_second': 4.313,
  'eval_steps_per_second': 0.539,
  'epoch': 3.0,
  'step': 600},
 {'train_runtime': 5671.4045,
  'train_samples_per_second': 0.846,
  'train_steps_per_second': 0.106,
  'total_flos': 631466532864000.0,
  'train_loss': 0.31641422073046366,
  'epoch': 3.0,
  'step': 600},
 {'eval_loss': 0.2724872827529907,
  'eval_accuracy': 0.915,
  'eval_precision': 0.8932038834951457,
  'eval_recall': 0.9387755102040817,
  'eval_f1': 0.9154228855721394,
  'eval_runtime': 49.311,
  'eval_samples_per_second': 4.056,
  'eval_steps_per_second': 0.507,
  'epoch': 3.0,
  'step': 600}]

In [55]:
from sklearn.metrics import confusion_matrix

pred = trainer.predict(test_dataset)
y_pred_ft = pred.predictions.argmax(axis=1)

print(confusion_matrix(test_labels, y_pred_ft))

c:\venv\bert\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

[[93 10]
 [ 7 90]]

In [56]:
print(trainer.state.global_step)

600

In [57]:
print(trainer.state.global_step)
print(trainer.state.epoch)
trainer.state.log_history

600
3.0

[{'loss': 0.7616782188415527,
  'grad_norm': 8.172735214233398,
  'learning_rate': 1.936666666666667e-05,
  'epoch': 0.1,
  'step': 20},
 {'loss': 0.6889323234558106,
  'grad_norm': 4.492760181427002,
  'learning_rate': 1.8700000000000004e-05,
  'epoch': 0.2,
  'step': 40},
 {'loss': 0.6903156757354736,
  'grad_norm': 3.7297415733337402,
  'learning_rate': 1.8033333333333332e-05,
  'epoch': 0.3,
  'step': 60},
 {'loss': 0.6684160709381104,
  'grad_norm': 6.493052005767822,
  'learning_rate': 1.7366666666666668e-05,
  'epoch': 0.4,
  'step': 80},
 {'loss': 0.5684875965118408,
  'grad_norm': 5.666116714477539,
  'learning_rate': 1.67e-05,
  'epoch': 0.5,
  'step': 100},
 {'loss': 0.473414945602417,
  'grad_norm': 6.023988246917725,
  'learning_rate': 1.6033333333333335e-05,
  'epoch': 0.6,
  'step': 120},
 {'loss': 0.41500306129455566,
  'grad_norm': 14.102923393249512,
  'learning_rate': 1.5366666666666666e-05,
  'epoch': 0.7,
  'step': 140},
 {'loss': 0.3562354803085327,
  'grad_norm': 5.605353832244873,
  'learning_rate': 1.4700000000000002e-05,
  'epoch': 0.8,
  'step': 160},
 {'loss': 0.3685903549194336,
  'grad_norm': 19.762088775634766,
  'learning_rate': 1.4033333333333335e-05,
  'epoch': 0.9,
  'step': 180},
 {'loss': 0.32598888874053955,
  'grad_norm': 7.301455974578857,
  'learning_rate': 1.3366666666666669e-05,
  'epoch': 1.0,
  'step': 200},
 {'eval_loss': 0.3695172071456909,
  'eval_accuracy': 0.85,
  'eval_precision': 0.7698412698412699,
  'eval_recall': 0.9897959183673469,
  'eval_f1': 0.8660714285714286,
  'eval_runtime': 45.3559,
  'eval_samples_per_second': 4.41,
  'eval_steps_per_second': 0.551,
  'epoch': 1.0,
  'step': 200},
 {'loss': 0.25046205520629883,
  'grad_norm': 0.8230054974555969,
  'learning_rate': 1.27e-05,
  'epoch': 1.1,
  'step': 220},
 {'loss': 0.2848529815673828,
  'grad_norm': 0.5980401039123535,
  'learning_rate': 1.2033333333333334e-05,
  'epoch': 1.2,
  'step': 240},
 {'loss': 0.31726484298706054,
  'grad_norm': 2.0508742332458496,
  'learning_rate': 1.1366666666666667e-05,
  'epoch': 1.3,
  'step': 260},
 {'loss': 0.23684582710266114,
  'grad_norm': 7.794430732727051,
  'learning_rate': 1.0700000000000001e-05,
  'epoch': 1.4,
  'step': 280},
 {'loss': 0.49371185302734377,
  'grad_norm': 44.501922607421875,
  'learning_rate': 1.0033333333333334e-05,
  'epoch': 1.5,
  'step': 300},
 {'loss': 0.23514795303344727,
  'grad_norm': 22.061084747314453,
  'learning_rate': 9.366666666666668e-06,
  'epoch': 1.6,
  'step': 320},
 {'loss': 0.27400434017181396,
  'grad_norm': 6.877014636993408,
  'learning_rate': 8.700000000000001e-06,
  'epoch': 1.7,
  'step': 340},
 {'loss': 0.25386526584625246,
  'grad_norm': 15.41490364074707,
  'learning_rate': 8.033333333333335e-06,
  'epoch': 1.8,
  'step': 360},
 {'loss': 0.2361302375793457,
  'grad_norm': 12.400002479553223,
  'learning_rate': 7.3666666666666676e-06,
  'epoch': 1.9,
  'step': 380},
 {'loss': 0.2669623136520386,
  'grad_norm': 2.248260498046875,
  'learning_rate': 6.700000000000001e-06,
  'epoch': 2.0,
  'step': 400},
 {'eval_loss': 0.27200472354888916,
  'eval_accuracy': 0.915,
  'eval_precision': 0.8932038834951457,
  'eval_recall': 0.9387755102040817,
  'eval_f1': 0.9154228855721394,
  'eval_runtime': 47.6064,
  'eval_samples_per_second': 4.201,
  'eval_steps_per_second': 0.525,
  'epoch': 2.0,
  'step': 400},
 {'loss': 0.12505544424057008,
  'grad_norm': 0.5733314156532288,
  'learning_rate': 6.033333333333335e-06,
  'epoch': 2.1,
  'step': 420},
 {'loss': 0.13173097372055054,
  'grad_norm': 0.24213434755802155,
  'learning_rate': 5.366666666666666e-06,
  'epoch': 2.2,
  'step': 440},
 {'loss': 0.12469862699508667,
  'grad_norm': 0.16621658205986023,
  'learning_rate': 4.7e-06,
  'epoch': 2.3,
  'step': 460},
 {'loss': 0.1724371552467346,
  'grad_norm': 40.822818756103516,
  'learning_rate': 4.033333333333333e-06,
  'epoch': 2.4,
  'step': 480},
 {'loss': 0.1815705418586731,
  'grad_norm': 0.20357532799243927,
  'learning_rate': 3.366666666666667e-06,
  'epoch': 2.5,
  'step': 500},
 {'loss': 0.13165069818496705,
  'grad_norm': 0.11804614216089249,
  'learning_rate': 2.7000000000000004e-06,
  'epoch': 2.6,
  'step': 520},
 {'loss': 0.08337968587875366,
  'grad_norm': 27.4355525970459,
  'learning_rate': 2.0333333333333335e-06,
  'epoch': 2.7,
  'step': 540},
 {'loss': 0.13633375167846679,
  'grad_norm': 0.8122232556343079,
  'learning_rate': 1.3666666666666668e-06,
  'epoch': 2.8,
  'step': 560},
 {'loss': 0.16794941425323487,
  'grad_norm': 0.2881026864051819,
  'learning_rate': 7.000000000000001e-07,
  'epoch': 2.9,
  'step': 580},
 {'loss': 0.07131004333496094,
  'grad_norm': 0.12846942245960236,
  'learning_rate': 3.333333333333334e-08,
  'epoch': 3.0,
  'step': 600},
 {'eval_loss': 0.39127877354621887,
  'eval_accuracy': 0.905,
  'eval_precision': 0.9157894736842105,
  'eval_recall': 0.8877551020408163,
  'eval_f1': 0.9015544041450777,
  'eval_runtime': 46.3726,
  'eval_samples_per_second': 4.313,
  'eval_steps_per_second': 0.539,
  'epoch': 3.0,
  'step': 600},
 {'train_runtime': 5671.4045,
  'train_samples_per_second': 0.846,
  'train_steps_per_second': 0.106,
  'total_flos': 631466532864000.0,
  'train_loss': 0.31641422073046366,
  'epoch': 3.0,
  'step': 600},
 {'eval_loss': 0.2724872827529907,
  'eval_accuracy': 0.915,
  'eval_precision': 0.8932038834951457,
  'eval_recall': 0.9387755102040817,
  'eval_f1': 0.9154228855721394,
  'eval_runtime': 49.311,
  'eval_samples_per_second': 4.056,
  'eval_steps_per_second': 0.507,
  'epoch': 3.0,
  'step': 600}]

In [58]:
test_result = trainer.evaluate(test_dataset)
print(test_result)

c:\venv\bert\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.31189435720443726, 'eval_accuracy': 0.915, 'eval_precision': 0.9, 'eval_recall': 0.9278350515463918, 'eval_f1': 0.9137055837563451}

In [59]:
test_result = trainer.evaluate(test_dataset)
print(test_result)

c:\venv\bert\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.31189435720443726, 'eval_accuracy': 0.915, 'eval_precision': 0.9, 'eval_recall': 0.9278350515463918, 'eval_f1': 0.9137055837563451}